// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW3Nsu_E3Ynsj6nMKiw0d5RFNYQEUcWq4',
    appId: '1:129797333121:web:e456d6e38645f052d8ed80',
    messagingSenderId: '129797333121',
    projectId: 'my-team-manager-f3fcb',
    authDomain: 'my-team-manager-f3fcb.firebaseapp.com',
    storageBucket: 'my-team-manager-f3fcb.appspot.com',
    measurementId: 'G-KW15SYMYCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4oaFvNjZ0Avu0kaLkyysvudkdJpjjquk',
    appId: '1:129797333121:android:1f11a50359e078e9d8ed80',
    messagingSenderId: '129797333121',
    projectId: 'my-team-manager-f3fcb',
    storageBucket: 'my-team-manager-f3fcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJzMKUt3TGkq6A-ij1pyXroR2vVPLGP8',
    appId: '1:129797333121:ios:d5e9af4e2aa09c49d8ed80',
    messagingSenderId: '129797333121',
    projectId: 'my-team-manager-f3fcb',
    storageBucket: 'my-team-manager-f3fcb.appspot.com',
    iosClientId: '129797333121-ofgoi31v7hnf0066p06jtrarp6i7sppp.apps.googleusercontent.com',
    iosBundleId: 'com.myteammanager.myTeamManager',
  );
}
